services:
  kestra:
    image: kestra/kestra:latest-full
    ports:
      - "8080:8080"
    volumes:
      - kestra-data:/app/storage
    environment:
      - KESTRA_STORAGE_TYPE=local
      - KESTRA_STORAGE_LOCAL_basePath=/app/storage
      - KESTRA_QUEUE_TYPE=memory
      - KESTRA_REPOSITORY_TYPE=h2
    command: server standalone

volumes:
  kestra-data:
